import "@/app/globals.css";
import CurrentSong from "@/components/player-section/current-song";
import PlayerMusic from "@/components/player-section/player-music";
import PlayerPlanel from "@/components/player-section/player-panel";
import { CircularStd } from "@/font-loader";
import ProviderResizable from "@/provider/provider-resizable";
import ProviderSession from "@/provider/provider-session";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Spotify Clone",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ProviderSession>
            <html lang="en">
                <body className={CircularStd.className}>
                    <div id="app">
                        <ProviderResizable>{children}</ProviderResizable>
                        <section className="flex justify-between p-3">
                            <CurrentSong />
                            <PlayerMusic />
                            <PlayerPlanel />
                        </section>
                    </div>
                </body>
            </html>
        </ProviderSession>
    );
}
